### ISSUE TITLE
Is "nslookup" a good name?

### ISSUE THREAD

**Issue by bortzmeyer** [QratorLabs/measurement_tools#2]
First, nslookup is an old and deprecated tool.

Second, I don't understand what atlas-nslookupmap does. Seeing the list of my measurements, I see only ping measurements, no DNS at all.

**Comment by euskov** [comment]
Indeed, the name was somewhat confusing. In the new release we changed it to `dnsmap'.
This tool creates a map of resolving results for the target. A good use case is a target with geo-based DNS.
This tool is also based on ping measurements since these measurements provide DNS resolve results besides the latency values.
